### ISSUE TITLE
How to load external template

### ISSUE THREAD

**Issue by jonathanyee** [mlaval/angular2-react-native-seed#1]
```
@Component({
    selector: 'as-users',
    templateUrl: './users.html'
})
```

I get `console.error: "Unhandled Promise rejection:", "Failed to load users.html", "; Zone: ", "<root>", "; Task:", "Promise,then", "; Value:', "Failed to load users.html", undefined.

users.html is in the same directory as this component

**Comment by mlaval** [comment]
See answer in https://github.com/angular/react-native-renderer/issues/87
