### ISSUE TITLE
Android APK/Application size too large even for "Hello World" text

### ISSUE THREAD

**Issue by sweety-wo** [mlaval/angular2-react-native-seed#4]
If i create APK with "Hello World" text, generated APK is of 4.00MB+ when using "splits enable true" and when i try installing that APK in some android device...application installed is of 24.00MB+.

So i am not sure what is taking this much space when i am just printing hello world text using this project.

Can you please let me know how can i reduce this APK/Application sizes.

Thanks.

**Comment by mlaval** [comment]
From what I can see, 4MB seems to be the minimum size for a React Native application.
See: http://stackoverflow.com/questions/38184734/react-native-for-small-size-apk-with-low-internet-bandwidth

It could only be improved by https://github.com/facebook/react-native itself.

**Comment by sweety-wo** [comment]
Thank you for replying... i understand that 4 MB is quite good to start with but my concern is of application size mainly which is 24.00MB+ which seems really large to me..

Is it a normal case?? or i may be doing something wrong..I am really new with this technologies.

Thanks again..
