### ISSUE TITLE
Attempted to set the key with value on object that is meant to be immutable and has been frozen.

### ISSUE THREAD

**Issue by sweety-wo** [mlaval/angular2-react-native-seed#5]
I just took clone this project and try to run it locally and it run fine but when i click on button "Show More" it start throwing me an error as below:

![image](https://cloud.githubusercontent.com/assets/14175105/19426171/3d675928-93ef-11e6-9eeb-3015c560a091.png)

Previously it was working perfectly when i cloned lastly but new one throws this error...

Do you know how can i solve this??

NOTE: Also if i build release apk and try testing it in local or in real device it work well but debug apk doesn't seem to work.

Thank you..!!

**Comment by mlaval** [comment]
Fixed in ecfa61179bd4aa08bf8f6a3a492433eb9888ea58

**Comment by sweety-wo** [comment]
@mlaval i took pull and deleted node_modules as well as regenerated it but still it keeps throwing same error on "Show More" button click..please let me know if i need to do anything else except this?

**Comment by sweety-wo** [comment]
Ahh Got it..it require me to do "gulp init" again once node_modules regenerated.. Thank you for fixing this..
