### ISSUE TITLE
gulp init report error

### ISSUE THREAD

**Issue by six006** [mlaval/angular2-react-native-seed#6]
Running C:\Android-Adt-Bundle\sdk/platform-tools/adb -s 192.168.30.102:5555 reverse tcp:8081 tcp:8081

Could not run adb reverse: Command failed: C:\Android-Adt-Bundle\sdk/platform-tools/adb -s 192.168.30.102:5555 reverse tcp:8081 tcp:8081

Building and installing the app on the device (cd android && gradlew.bat installDebug...

Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

[23:02:11] Finished '!launch.android' after 7.3 s
[23:02:11] Starting '!start.android'...
Scanning 715 folders for symlinks in H:\Javascript\Angular-Reactnative\angular2-react-native-seed-master\dist\ngRnSeed\node_modules (145ms)

 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   H:\Javascript\Angular-Reactnative\angular2-react-native-seed-master\dist\ngRnSeed

[2016-10-20 23:02:18] <START> Building Dependency Graph

[2016-10-20 23:02:18] <START> Crawling File System

 ERROR  Packager can't listen on port 8081

Most likely another process is already using this port
Run the following command to find out which process:

   lsof -n -i4TCP:8081

You can either shut down the other process:

   kill -9 <PID>

or run packager on different port.

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

{ Error: Command failed: react-native start

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 11,
  signal: null,
  cmd: 'react-native start' }

**Comment by mlaval** [comment]
Issue fixed, at least for the second part of the log.

No idea for the first part:
```
Running C:\Android-Adt-Bundle\sdk/platform-tools/adb -s 192.168.30.102:5555 reverse tcp:8081 tcp:8081

Could not run adb reverse: Command failed: C:\Android-Adt-Bundle\sdk/platform-tools/adb -s 192.168.30.102:5555 reverse tcp:8081 tcp:8081
```
It doesn't seem linked to this project as `adb` is failing here... Please try again with the fix.
